import "./globals.css";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {
  children: React.ReactNode;
}) {

  let cookie = cookies().get('mode')
  // console.log(cookie)


  return (
    <html lang="en">
      <body className="overflow-y-scroll">
        <DarkMode/>
        {children}
      </body>
    </html>
  );
}
