import "./globals.css";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";



export const metadata = {
  title: "ChangHyun Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let cookie = cookies().get("mode");


  // ${cookie!= undefined && cookie.value == 'dark' ? 'dark-mode' : ''}

  return (
    <html lang="en">
      <body className={`${cookie != undefined && cookie.value == 'dark' ? 'dark-mode' : ''} overflow-y-scroll`}>
        <DarkMode />
        {children}
      </body>
    </html>
  );
}
